#!/usr/bin/env bash
alias bc='bc -l'
alias dcd='docker-compose down'
alias dcr='dcd && dcu'
alias dcu='docker-compose up'
alias dps='docker ps'
alias gb='git branch -a'
alias gp='git remote prune origin'
alias ll='ls -al'
alias vd='vagrant destroy -f'
alias vr='vd && vu'
alias vs='vagrant status'
alias vssh='vagrant ssh'
alias vu='time vagrant up'
